syntax = "proto3";

package user;

option go_package = "github.com/gin-demo/api/pb/user";

service UserService {
    // 统一接口有接收request和返回response
    rpc Handle(UserRequest) returns (UserResponse);
}

message UserRequest {
    oneof payload {
        RegisterRequest register_request = 1;
        LoginRequest login_request = 2;
        GetUserRequest get_user_request = 3;
        UpdateUserRequest update_user_request = 4;
        ListUsersRequest list_users_request = 5;
    }
}


message RegisterRequest {
    string username = 1;
    string password = 2;
    string email = 3;
}
//回来改成单点登录
message LoginRequest {
    string username = 1;
    string password = 2;
}

message GetUserRequest {
    int64 user_id = 1;
}

message UpdateUserRequest {
    int64 user_id = 1;
    optional string nickname = 2;
    optional string avatar = 3;
    optional string email = 4;
}

message ListUsersRequest {
    uint32 page = 1;
    uint32 page_size = 2;
    string keyword = 3;
}




message UserResponse {
    uint32 code = 1;
    string message =2;
    oneof payload {
        RegisterResponse register_response = 3;
        LoginResponse login_response = 4;
        GetUserResponse get_user_response = 5;
        UpdateUserResponse update_user_response = 6;
        ListUsersResponse list_users_response = 7;
    }
}

message RegisterResponse {
    uint64 user_id = 1;
}


message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message GetUserResponse {
    User user_data = 1;
}

message UpdateUserResponse {
    bool success = 1;
}

message ListUsersResponse {
    repeated User users = 1;
    uint32 total = 2;
}

message User {
    uint64 user_id = 1;
    string username = 2;
    string nickname = 3;
    string avatar = 4;
    string email = 5;
    int32 status = 6;
    int64 created_at = 7;
    int64 updated_at = 8;
}

